version: "3.9"

services:
  finetune:
    container_name: luotuo
    build: ./docker
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_IP=0.0.0.0
      - JUPYTER_PORT=8888
      - http_proxy=http://10.102.65.102:1450
      - https_proxy=http://10.102.65.102:1450
      - PYPI_MIRROR=https://pypi.tuna.tsinghua.edu.cn/simple
      - TRANSFORMERS_CACHE=/workspace/.cache/huggingface/transformers/
      - HF_DATASETS_CACHE=/workspace/.cache/huggingface/
    volumes:
      - ./.jupyter:/root/.jupyter
      - ./:/workspace
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']    # Fill your GPU id here(Get it from nvidia-smi -L)
            capabilities: [gpu]